// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCF593Plk3x2auzEQxvSyNlbnDF3AOJkWI',
    appId: '1:755822605327:web:d681c13048139d14831f7a',
    messagingSenderId: '755822605327',
    projectId: 'caretutors-59254',
    authDomain: 'caretutors-59254.firebaseapp.com',
    storageBucket: 'caretutors-59254.firebasestorage.app',
    measurementId: 'G-1C0NKWZ1CK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIurIaZrd1rG70MnnD2zLRj9JQ8E7vD5Q',
    appId: '1:755822605327:android:45e64a79a1990005831f7a',
    messagingSenderId: '755822605327',
    projectId: 'caretutors-59254',
    storageBucket: 'caretutors-59254.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAr6n4E80dLeNyuXH3M4frm8bSO022zRk',
    appId: '1:755822605327:ios:2db177435d957d6f831f7a',
    messagingSenderId: '755822605327',
    projectId: 'caretutors-59254',
    storageBucket: 'caretutors-59254.firebasestorage.app',
    iosBundleId: 'caretutos.app.caretutorProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAr6n4E80dLeNyuXH3M4frm8bSO022zRk',
    appId: '1:755822605327:ios:2db177435d957d6f831f7a',
    messagingSenderId: '755822605327',
    projectId: 'caretutors-59254',
    storageBucket: 'caretutors-59254.firebasestorage.app',
    iosBundleId: 'caretutos.app.caretutorProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCF593Plk3x2auzEQxvSyNlbnDF3AOJkWI',
    appId: '1:755822605327:web:361523146bd62e65831f7a',
    messagingSenderId: '755822605327',
    projectId: 'caretutors-59254',
    authDomain: 'caretutors-59254.firebaseapp.com',
    storageBucket: 'caretutors-59254.firebasestorage.app',
    measurementId: 'G-ECKFK2EPHW',
  );
}
